image: node:20

pipelines:
  custom:
    api-tests:
      - variables:
        - name: ENVIRONMENT
          allowed-values: ['staging', 'prod']
          default: 'staging'
        - name: TENANT
          default: 'syracuse'
          allowed-values: ['libertyuni-th', 'umichigan-th', 'syracuse', 'fsuni-staging', 'ucla']
        - name: API_VERSION
          allowed-values: ['v2', 'v2.1']
          default: 'v2'

      - stage:
          name: Test

          steps:
            - step:
                caches:
                  - node
                script:
                  - npm install
                  - >
                    if [ "$API_VERSION" == "v2" ]; then
                      npm test -- --testPathPattern=tests/v2/;
                    else
                      npm test -- tests/v2.1;
                    fi

options:
  max-time: 10
