require('dotenv').config();

const config = {
    env: process.env.ENVIRONMENT,
    baseURL: process.env.ENVIRONMENT === 'prod' ? process.env.PROD_BASE_URL : process.env.STAGE_BASE_URL,
    tenant: process.env.TENANT,
    version: process.env.API_VERSION,
    awardID: 553,
    awardTypeID: 1,
    categoryID: 33,
    documentID: 46552,
    startDATE: '2024-08-01T11:00:00',
    endDATE: '2024-08-10T11:00:00',
    facilityID: 11,
    galleryID: 5480,
    gameID: 13803,
    locationINDICATOR: 'N',
    opponentID: 118,
    pageINDEX: 2,
    pageSIZE: 3,
    playerID: 6097,
    playerLastNameSTART: 'Aa',
    playerNAME: 'Bryan',
    pressClipID: 1,
    rosterID: 438,
    rosterPlayerID: 14528,
    scheduleID: 443,
    searchTEXT: 'Director of Athletics',
    storyHeadlinePartialText: 'Orange',
    storyID: 25495,
    storyName: 'track-and-field-doan-places-27th-in-us-olympic-trials-steeplechase-debut',
    tagSLUG: 'florida-state',
    videoCategoryTYPE: 'live',
    videoType: 'youtube',
    sportTITLE: 'Baseball',
    seasonID: 49,
    sportID: 1,
    seasonYEAR: '2024',
    sportLIGHT: true,
    sportNameSlug: 'baseball',
    seriesID: 1,
    staffID: 7190,
    storyDate: '2024-06-24T21:55:00',
    podcastID: 6,
    
};

module.exports = config;
